"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _tarjeta_libro from './tarjeta-libro.bones.json'

registerBones({
  "tarjeta-libro": _tarjeta_libro,
})
